# Generated by Django 4.2.7 on 2024-01-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('mailid', models.CharField(max_length=50)),
                ('experiance', models.IntegerField(null=True)),
                ('status', models.CharField(default='Active', editable=False, max_length=50)),
            ],
            options={
                'db_table': 'doctor_register',
            },
        ),
    ]
