# Generated by Django 4.2.7 on 2024-01-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0002_doctor_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Model',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('status', models.CharField(default='Active', editable=False, max_length=50)),
            ],
            options={
                'db_table': 'user_register',
            },
        ),
    ]
