# Generated by Django 4.2.7 on 2024-01-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0003_user_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_Model',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('u_id', models.IntegerField(null=True)),
                ('message', models.CharField(max_length=50)),
                ('reply_msg', models.CharField(max_length=50)),
                ('doc_id', models.IntegerField(null=True)),
                ('doc_cno', models.CharField(max_length=50)),
                ('status', models.CharField(default='not seen', editable=False, max_length=50)),
            ],
            options={
                'db_table': 'chatbox',
            },
        ),
    ]
