# Generated by Django 4.2.7 on 2024-01-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0004_chat_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_model',
            name='doc_cno',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='chat_model',
            name='doc_id',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='chat_model',
            name='reply_msg',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
