# Generated by Django 5.0.2 on 2024-02-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0006_history_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_model',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
