# Generated by Django 5.0.2 on 2024-02-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0007_history_model_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_model',
            name='reply_msg',
            field=models.CharField(max_length=50),
        ),
    ]
