# Generated by Django 5.0.2 on 2024-02-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0008_alter_history_model_reply_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_model',
            name='reply_msg',
            field=models.TextField(max_length=50),
        ),
    ]
