# Generated by Django 5.0.2 on 2024-02-17 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0009_alter_history_model_reply_msg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor_model',
            old_name='experiance',
            new_name='experience',
        ),
    ]
