# Generated by Django 5.2 on 2025-05-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0010_rename_experiance_doctor_model_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_model',
            name='hospital_or_clinic_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctor_model',
            name='time',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Full Time', 'Full Time')], max_length=100, null=True),
        ),
    ]
