# Generated by Django 5.2 on 2025-05-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0011_doctor_model_hospital_or_clinic_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_model',
            name='doc_name',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
