# Generated by Django 5.2 on 2025-05-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0012_chat_model_doc_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_model',
            name='key',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
