# Generated by Django 5.2 on 2025-05-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0013_chat_model_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_model',
            name='u_mail',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
