# Generated by Django 5.2 on 2025-05-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0014_chat_model_u_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='mail',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
