# Generated by Django 5.2 on 2025-05-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0015_user_model_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history_model',
            name='message',
        ),
        migrations.RemoveField(
            model_name='history_model',
            name='reply_msg',
        ),
        migrations.AddField(
            model_name='history_model',
            name='did',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='history_model',
            name='dmail',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='history_model',
            name='dname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='history_model',
            name='umail',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='history_model',
            name='uname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
